---
_extends: template

repository:
  name: toktok-stack
  description: A snapshot of the complete software stack (excluding some external libraries and programs)
  has_issues: true

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - Codacy/PR Quality Review
          - Travis CI - Pull Request
          - WIP
          - cirrus-ci
          - code-review/reviewable
          - license/cla
