---
_extends: .github

repository:
  name: toktok-stack
  description: A snapshot of the complete software stack (excluding some external libraries and programs)
  topics: bazel, tox

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - "common / buildifier"
          - "docker-test"
          - "LGTM analysis: Go"
          - "LGTM analysis: Python"
          - "mypy"
