---
cirrus-ci_task:
  container:
    image: l.gcr.io/google/bazel:3.0.0
    cpu: 8
    memory: 12G
  configure_script:
    - git submodule update --init --depth=5 --recursive
  test_all_script:
    - bazel test -k
        --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
        --config=ci
        --config=clang
        --config=release
        //c-toxcore/...
        //go-toxcore-c/...
        //jtox/...
        //jvm-macros/...
        //jvm-toxcore-api/...
        //jvm-toxcore-c/...
        //py_toxcore_c/...
        //toxins/...
