---
cirrus-ci_task:
  container:
    image: ubuntu:latest
    cpu: 8
    memory: 12G
  configure_script:
    - make
  test_all_script:
    - make run TARGET="
      //c-toxcore/...
      //go-toxcore-c/...
      //jtox/...
      //jvm-toxcore-api/...
      //jvm-toxcore-c/...
      //py_toxcore_c/...
      //toxins/..."
