---
cirrus-ci_docker_builder:
  dependencies_script:
    - git submodule update --init --depth=20 --recursive
    - tools/project/update_versions.sh
  docker_build_script:
    - make
  bazel_build_script:
    - docker run --rm toxchat/toktok-stack:latest bazel build
      --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
      //c-toxcore/...
      //go-toxcore-c/...
      //jtox/...
      //jvm-toxcore-api/...
      //jvm-toxcore-c/...
      //py_toxcore_c/...
      //toxic/...
      //toxins/...
