---
exclude:
  - "**/BUILD.*"
  - "third_party/ffmpeg/**/*.[ch]"
  - "third_party/haskell/alex/templates/*.hs"
  - "third_party/haskell/happy/templates/*"
  - "third_party/libsodium/version.h"
  - "third_party/libzmq/**/*.hpp"
  - "third_party/libvpx/**/*.h"
  - "third_party/libvpx/**/*.mk"
  - "third_party/ncurses/src/**/*"
  - "third_party/opus/**/*.h"
