---
exclude:
  - "**/BUILD.*"
  - "third_party/ffmpeg/**/*.[ch]"
  - "third_party/haskell/alex/templates/*.hs"
  - "third_party/haskell/happy/templates/*"
  - "third_party/libsodium/version.h"
  - "third_party/libzmq/**/*.hpp"
