version: "0.2"
ignorePaths:
  - c-toxcore/**
  - "*bazelrc*"
words:
  - asan
  - bazel
  - bazelisk
  - buildx
  - fastbuild
  - LIBC
  - libfuzzer
  - mypy
  - nixpkgs
  - patchelf
  - toktok
  - toxchat
  - toxcore
