flags:
  HDBC:
    mintime15: false
  pandoc:
    old-locale: true
  iso8601-time:
    new-time: false
packages:
#- github-tools/
- hs-msgpack/
#- hs-msgpack-rpc/
#- hs-schema/
#- hs-toxcore/
#- hs-toxcore-c/
#- semdoc/
#- tokstyle/
#- website/
extra-deps:
- HDBC-2.4.0.1
- HDBC-sqlite3-2.3.3.1
- QuickCheck-2.9.2
- aeson-compat-0.3.6
- asn1-parse-0.9.4
- asn1-types-0.3.2
- base-compat-0.9.1
- binary-bits-0.5
- binary-conduit-1.2.4.1
- binary-orphans-0.1.5.1
- bytestring-arbitrary-0.1.0
- call-stack-0.1.0
- cmark-0.5.4
- conduit-extra-1.1.15
- connection-0.2.6
- cpphs-1.20.2
- cryptonite-0.20
- github-0.15.0
- groom-0.1.2
- highlighting-kate-0.6.3
- hspec-2.3.2
- hspec-core-2.3.2
- hspec-discover-2.3.2
- hspec-expectations-0.8.2
- http-api-data-0.2.4
- http-client-0.4.31.1
- http-link-header-1.0.3
- integer-simple-0.1.1.1
- iso8601-time-0.1.4
- memory-0.13
- pandoc-1.16
- pandoc-types-1.16
- primitive-0.6.1.0
- quickcheck-io-0.1.4
- saltine-0.0.0.4
- servant-0.5
- servant-server-0.5
- socks-0.5.5
- streaming-commons-0.1.16
- texmath-0.8.6.7
- time-locale-compat-0.1.1.3
- tls-1.3.8
- uri-bytestring-0.2.2.0
- vector-0.11.0.0
- vector-algorithms-0.7.0.1
- vector-binary-instances-0.2.3.3
- vector-instances-3.3.1
- vector-th-unbox-0.2.1.6
- x509-1.6.4
- x509-store-1.6.2
- x509-system-1.6.4
- x509-validation-1.6.5
resolver: lts-2.22
