---
packages:
  - hs-apigen/
  - hs-cimple/
  - hs-github-tools/
  - hs-msgpack-arbitrary/
  - hs-msgpack-binary/
  - hs-msgpack-rpc-conduit/
  - hs-msgpack-testsuite/
  - hs-msgpack-types/
  - hs-schema/
  - hs-tokstyle/
  - hs-toxcore/
  - hs-toxcore-c/
resolver: lts-21.9
extra-deps:
  - monad-validate-1.3.0.0
  - suspend-0.2.0.0
  - timers-0.2.0.4
allow-newer: true
