#!/usr/bin/env python3
import re
import subprocess
import sys

SYMBOLIZER = (
    "/nix/store/d0r6r274cpcr6gslqx16gn0m38qpy5p3-llvm-16.0.6/bin/llvm-symbolizer"
)

REGEX = r"\b(0x[0-9a-f]{8,})  \(([^ +]*)\+(0x[0-9a-f]+)\)"

for line in sys.stdin:
    m = re.search(REGEX, line.strip())
    if m:
        addr = m.group(1)
        prog = m.group(2)
        off = m.group(3)

        try:
            fun = (subprocess.run(
                [SYMBOLIZER, "--pretty-print", f"--exe={prog}", off],
                check=True,
                capture_output=True,
            ).stdout.decode("utf-8").split("\n")[0])
            print(re.sub(REGEX, fun, line), end="")
        except subprocess.CalledProcessError:
            print(line, end="")
    else:
        print(line, end="")
