name: ci

on:
  pull_request:
    branches: [master]

jobs:
  build:
    uses: TokTok/ci-tools/.github/workflows/haskell-ci.yml@master

  common:
    uses: TokTok/ci-tools/.github/workflows/common-ci.yml@master
