FROM toxchat/toktok-stack:latest

RUN \
 if curl -s -m1 http://code.tox.chat/bazel/ \
   | grep "resource name must be a SHA256 hash"; then \
   echo 'build --config=remote' | tee -a .bazelrc.local; \
 fi; \
 sed -i -e 's/build --config=nix/build --config=windows-x86_64/' .bazelrc

RUN sudo nix-daemon --daemon & bazel build -k //c-toxcore/toxcore

# vim:ft=dockerfile
