# Pre-build //... in release mode for speedy PR builds on sub-repos.
FROM toxchat/toktok-stack:latest

RUN echo 'build --config=release' >>.local.bazelrc

RUN sudo nix-daemon --daemon & bazel build -k //...

# vim:ft=dockerfile
