# Pre-build //third_party in debug mode for speedy PR builds on sub-repos.
FROM toxchat/toktok-stack:latest

RUN echo 'build --config=debug'  >> .bazelrc.local

RUN sudo nix-daemon --daemon & bazel build -k //third_party/...

# vim:ft=dockerfile
