FROM toxchat/toktok-stack:latest

RUN \
 if curl -s -m1 http://code.tox.chat/bazel/ \
   | grep "resource name must be a SHA256 hash"; then \
   echo 'build --config=remote' | tee -a .bazelrc.local; \
 fi; \
 sed -i -e 's/build --config=nix/build --config=linux-arm64-musl/' .bazelrc

RUN sudo nix-daemon --daemon & bazel build -k //c-toxcore/auto_tests/...

# vim:ft=dockerfile
