# Pre-build //third_party in debug mode for speedy PR builds on sub-repos.
FROM toxchat/toktok-stack:latest

RUN echo 'build --config=debug' >>.local.bazelrc

RUN sudo nix-daemon --daemon & bazel build -k \
 --build_tag_filters=-haskell \
 --test_tag_filters=-haskell \
 //c-toxcore/... \
 //third_party/...

# vim:ft=dockerfile
