# Pre-build //third_party in tsan mode for speedy PR builds on sub-repos.
FROM toxchat/toktok-stack:latest

RUN echo 'build --config=release' >> .bazelrc.local \
 && echo 'build --config=tsan'    >> .bazelrc.local

RUN ["bazel", "build", "-k", "--", "//third_party/...",  "-//third_party/haskell/..."]

# vim:ft=dockerfile
