# Pre-build //... in fastbuild mode for dev containers.
FROM toxchat/toktok-stack:latest

RUN echo 'build --config=remote' >> .bazelrc.local

RUN ["bazel", "build", "-k", "//..."]

# vim:ft=dockerfile
