# Pre-build //third_party in release mode for speedy PR builds on sub-repos.
FROM toxchat/toktok-stack:$VERSION

RUN echo 'build --config=release' > .bazelrc.local

RUN ["bazel", "build", "-k", "--config=remote", "//third_party/..."]
