#!/bin/bash

set -eux

REPO="$1"

# Symlink the toktok-stack source tree to the location where cirrus-ci expects
# it to be. Cirrus chdir's into /tmp/cirrus-ci-build on every action, so it must
# always exist.
cd /
mv /tmp/cirrus-ci-build /tmp/cirrus-ci-repo
mkdir /tmp/cirrus-ci-build
cd /tmp/cirrus-ci-build
for i in /src/workspace/* /src/workspace/.??*; do
  ln -s "$i" .
done
rm "$REPO"
mv /tmp/cirrus-ci-repo "$REPO"
cd /tmp/cirrus-ci-build

# Set up .bazelrc.local from the example in toktok-stack.
cp ".bazelrc.local.example" ".bazelrc.local"
if [ -f "$REPO/.bazelrc.local" ]; then
  # If the repo has customisations, add those here.
  cat "$REPO/.bazelrc.local" >> ".bazelrc.local"
fi
