#!/bin/sh

set -eux

REPO="$1"

cd /src/workspace
rm -rf "$REPO"
mv /tmp/cirrus-ci-build "$REPO"
mkdir /tmp/cirrus-ci-build

if [ -f "$REPO/.bazelrc.local" ]; then
  # If the repo has customisations, add those here.
  cp "$REPO/.bazelrc.local" ".bazelrc.local"
fi

# Disable remote caching for now (Cirrus doesn't seem to like gRPC).
sed -i -e 's/build --config=remote/# build --config=remote/' ".bazelrc.local"
