#!/bin/sh

set -eux

REPO="$1"

cd /src/workspace
rm -rf "$REPO"
mv /tmp/cirrus-ci-build "$REPO"
mkdir /tmp/cirrus-ci-build

if [ -f "$REPO/.local.bazelrc" ]; then
  # If the repo has customisations, add those here.
  cp "$REPO/.local.bazelrc" ".local.bazelrc"
fi

# Cirrus doesn't like gRPC.
sed -i -e 's/build --config=remote-grpc/build --config=remote-http/' ".local.bazelrc"
