#!/usr/bin/env bash

set -eux

NUM_ATTEMPTS="$1"
shift

readarray -t ATTEMPTS <<<"$(seq 1 "$NUM_ATTEMPTS")"

for i in "${ATTEMPTS[@]}"; do
  echo "=== Attempt $i ==="
  if "$@"; then
    exit 0
  fi
done

echo "Failed after $NUM_ATTEMPTS attempts: $@"
exit 1
