#!/usr/bin/perl

use strict;
use warnings;

my $ATTEMPTS = shift @ARGV;

for my $i (1 .. $ATTEMPTS) {
   print "=== Attempt $i ===\n";
   exit 0 unless system @ARGV;
}

print "Failed after $ATTEMPTS attempts: @ARGV\n";
exit 1;
