#!/bin/bash

echo '# Bazel configuration for toktok-stack'   | tee ~/.bazelrc
echo 'build --config=ci'                        | tee -a ~/.bazelrc
echo "build --config=$(basename "${CC-clang}")" | tee -a ~/.bazelrc

RESPONSE='resource name must be a SHA256 hash'

if curl -s -m1 https://code.tox.chat/bazel/ | grep "$RESPONSE"; then
  echo 'build --config=remote' | tee -a ~/.bazelrc
fi

# Download dependencies for streambot only if we're building it.
if [ -f echobot-jvm/BUILD.bazel ]; then
  wget https://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/ffmpeg/3.4.1-1.4/ffmpeg-3.4.1-1.4-linux-x86_64.jar -O third_party/javacpp/ffmpeg/jar/ffmpeg-3.4.1-1.4-linux-x86_64.jar
  wget https://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/opencv/3.4.0-1.4/opencv-3.4.0-1.4-linux-x86_64.jar -O third_party/javacpp/opencv/jar/opencv-3.4.0-1.4-linux-x86_64.jar
fi
