#!/bin/sh

set -eux

wget https://github.com/bazelbuild/bazel/releases/download/2.2.0/bazel-2.2.0-installer-linux-x86_64.sh
sha256sum -c tools/bazel-2.2.0-installer-linux-x86_64.sh.sha256
chmod +x bazel-2.2.0-installer-linux-x86_64.sh
./bazel-2.2.0-installer-linux-x86_64.sh --user
export PATH="$HOME/bin:$PATH"

set +eux
