#!/bin/sh

set -eux

wget https://github.com/bazelbuild/bazel/releases/download/4.2.1/bazel-4.2.1-installer-linux-x86_64.sh
sha256sum -c tools/bazel-4.2.1-installer-linux-x86_64.sh.sha256
chmod +x bazel-4.2.1-installer-linux-x86_64.sh
./bazel-4.2.1-installer-linux-x86_64.sh --user
export PATH="$HOME/bin:$PATH"

set +eux
